knp_paginator:
    page_range: 5                      # number of links shown in the pagination menu (e.g: you have 10 pages)
    default_options:
        page_name: page               # page query parameter name
        sort_field_name: sort         # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                # ensure distinct results, useful when ORM queries are using GROUP BY
        filter_field_name: filterField 
        filter_value_name: filterValue 
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'       
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'   
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  